KERNEL_SRC ?= /lib/modules/$(shell uname -r)/build
interface_type ?= pcie
emulation_build ?= 0
unified_driver ?= 0
M ?= $(shell pwd)

ifeq ($(unified_driver), 1)
KBUILD_OPTIONS += ROOTDIR=$(shell cd $(KERNEL_SRC); readlink -e $(M))
KBUILD_OPTIONS += MODNAME?=wlan_cnss_core_$(interface_type)
KBUILD_OPTIONS += WLAN_CNSSCORE=m
KBUILD_OPTIONS += CONFIG_WLAN_CNSS_CORE=y
KBUILD_OPTIONS += CONFIG_CNSS_OUT_OF_TREE=y
KBUILD_OPTIONS += CONFIG_QRTR=y CONFIG_QRTR_MHI=y CONFIG_CNSS_UTILS=y CONFIG_CNSS2=y CONFIG_CNSS2_QMI=y \
                  CONFIG_CNSS2_DEBUG=y CONFIG_CNSS2_X86=y CONFIG_QCOM_QMI_HELPERS=y CONFIG_CNSS_QMI_SVC=y
KBUILD_OPTIONS += CONFIG_CNSS2_SSR_DRIVER_DUMP=y
ifeq ($(interface_type), pcie)
KBUILD_OPTIONS += CONFIG_CNSS2_PCIE=y CONFIG_MHI_BUS=y CONFIG_MHI_BUS_DEBUG=y
ifeq ($(emulation_build), 1)
KBUILD_OPTIONS += CONFIG_PCIE_EMULATION=y
endif
endif

else #unified_driver 0
# $(WLAN_PLATFORM_ROOT) has to be a absolute path
ifeq ($(WLAN_PLATFORM_ROOT),)
WLAN_PLATFORM_ROOT = $(shell pwd)

# If it reaches here, compilation is probably without Android.mk,
# so enable all flags (including debug flag CONFIG_CNSS2_DEBUG) by
# default.
KBUILD_OPTIONS := WLAN_PLATFORM_ROOT=$(WLAN_PLATFORM_ROOT)
ifeq ($(WLAN_BASEMACHINE),qcs40x)
ifeq ($(CONFIG_FULL_CORE_TECH),y)
KBUILD_OPTIONS += CONFIG_QRTR=m
KBUILD_OPTIONS += CONFIG_QRTR_MHI=m
KBUILD_OPTIONS += CONFIG_MHI_BUS=m
KBUILD_OPTIONS += CONFIG_QCOM_QMI_HELPERS=m
endif
KBUILD_OPTIONS += CONFIG_CNSS_OUT_OF_TREE=y
KBUILD_OPTIONS += CONFIG_ICNSS2=m
KBUILD_OPTIONS += CONFIG_ICNSS2_QMI=y
KBUILD_OPTIONS += CONFIG_ICNSS2_DEBUG=y
KBUILD_OPTIONS += CONFIG_CNSS_QMI_SVC=m
KBUILD_OPTIONS += CONFIG_WCNSS_MEM_PRE_ALLOC=m
KBUILD_OPTIONS += CONFIG_CNSS_UTILS=m
KBUILD_OPTIONS += CONFIG_CNSS2_X86=y
KBUILD_OPTIONS += CONFIG_CNSS_GENL=m
else ifeq ($(USE_EXTERNAL_CONFIGS),)
ifeq ($(CONFIG_FULL_CORE_TECH),y)
KBUILD_OPTIONS += CONFIG_QRTR=m
KBUILD_OPTIONS += CONFIG_QRTR_MHI=m
KBUILD_OPTIONS += CONFIG_MHI_BUS=m
KBUILD_OPTIONS += CONFIG_QCOM_QMI_HELPERS=m
endif
KBUILD_OPTIONS += CONFIG_CNSS_OUT_OF_TREE=y
KBUILD_OPTIONS += CONFIG_CNSS2=m
KBUILD_OPTIONS += CONFIG_ICNSS2=m
KBUILD_OPTIONS += CONFIG_CNSS2_QMI=y
KBUILD_OPTIONS += CONFIG_ICNSS2_QMI=y
KBUILD_OPTIONS += CONFIG_CNSS2_DEBUG=y
KBUILD_OPTIONS += CONFIG_ICNSS2_DEBUG=y
KBUILD_OPTIONS += CONFIG_CNSS_QMI_SVC=m
KBUILD_OPTIONS += CONFIG_CNSS_GENL=m
KBUILD_OPTIONS += CONFIG_WCNSS_MEM_PRE_ALLOC=m
KBUILD_OPTIONS += CONFIG_CNSS_UTILS=m
KBUILD_OPTIONS += CONFIG_CNSS2_X86=y
KBUILD_OPTIONS += CONFIG_CNSS2_SSR_DRIVER_DUMP=y
endif
endif
endif #unified_driver end

all: modules

%:
	$(MAKE) -C $(KERNEL_SRC) M=$(M) $@ $(KBUILD_OPTIONS)

modules_install:
	$(MAKE) INSTALL_MOD_STRIP=1 -C $(KERNEL_SRC) M=$(M) modules_install

clean:
	$(MAKE) -C $(KERNEL_SRC) M=$(M) clean
